# Jupyter Notebook for Module Tasks
This notebook contains the solutions for the tasks of this module

## Task 1: Binary Representations

Create the following functions in Python, demonstrating their use with examples and tests.

1. The function `rotl(x, n=1)` that rotates the bits in a 32-bit unsigned integer to the left `n` places.

2. The function `rotr(x, n=1)` that rotates the bits in a 32-bit unsigned integer to the right `n` places.

3. The function `ch(x, y, z)` that chooses the bits from `y` where `x` has bits set to `1` and bits in `z` where `x` has bits set to `0`.

4. The function `maj(x, y, z)` which takes a majority vote of the bits in `x`, `y`, and `z`.  
The output should have a `1` in bit position `i` where at least two of `x`, `y`, and `z` have `1`'s in position `i`.  
All other output bit positions should be `0`.

## Task 1: Overall Plan

This task involves implementing four bitwise functions: `rotl`, `rotr`, `ch`, and `maj`.  
Each function will be developed individually, with a focus on correct handling of 32-bit unsigned integers by applying a bitmask (`0xFFFFFFFF`) after operations.  
For each function, example inputs and outputs will be provided in both binary and decimal formats to verify correctness and demonstrate functionality.

## Rough Outline

- Implement `rotl(x, n=1)`:
  - Rotate bits to the left, apply 32-bit masking.
  - Provide tests with simple inputs.
- Implement `rotr(x, n=1)`:
  - Rotate bits to the right, apply 32-bit masking.
  - Provide similar tests.
- Implement `ch(x, y, z)`:
  - Use bitwise logic to select bits from `y` or `z` based on `x`.
  - Provide tests with chosen values.
- Implement `maj(x, y, z)`:
  - Perform bitwise majority voting among the three inputs.
  - Provide example-based tests.
- Display both binary and decimal results throughout for clarity and verification.


### Understanding Bitwise Operations

Bitwise operations are fundamental to binary manipulation, especially in cryptographic algorithms like SHA-256.  
The following operators are used throughout the binary representations task:

- **Left Shift (`<<`)**  
  Moves all bits to the left by a specified number of positions.  
  Each left shift multiplies the number by `2`.  
  Example: `5 << 1` → `10`.

- **Right Shift (`>>`)**  
  Moves all bits to the right by a specified number of positions.  
  Each right shift approximately divides the number by `2`.  
  Example: `8 >> 1` → `4`.

- **Bitwise AND (`&`)**  
  Compares each bit of two numbers and returns `1` if both bits are `1`, otherwise returns `0`.  
  Example: `0b1100 & 0b1010` → `0b1000`.

- **Bitwise OR (`|`)**  
  Compares each bit of two numbers and returns `1` if at least one of the bits is `1`.  
  Example: `0b1100 | 0b1010` → `0b1110`.

- **Bitwise XOR (`^`)**  
  Compares each bit of two numbers and returns `1` if the bits are different, otherwise returns `0`.  
  Example: `0b1100 ^ 0b1010` → `0b0110`.

- **Bitwise NOT (`~`)**  
  Inverts each bit of the number: `1` becomes `0`, and `0` becomes `1`.  
  Example: `~0b00001111` → `0b11110000` (after considering 32-bit masking).

- **Masking with `0xFFFFFFFF`**  
  After shifting or other operations, numbers are masked to stay within 32 bits by using bitwise AND with `0xFFFFFFFF`.  
  Example: `(result) & 0xFFFFFFFF`.

These operations are essential for manipulating binary data accurately and efficiently.


## rotl(x, n=1)

The `rotl` function rotates the bits of a 32-bit unsigned integer `x` to the left by `n` positions.  
Bits that are shifted out from the left are reinserted on the right.  
A bitmask of `0xFFFFFFFF` is applied to ensure the result remains a 32-bit unsigned integer.


In [5]:
def rotl(x, n=1):
    """Rotate bits of a 32-bit unsigned integer to the left by n positions."""
    
    # Shift x left by n bits
    left_shifted = (x << n)
    
    # Shift x right by (32 - n) bits
    right_shifted = (x >> (32 - n))
    
    # Combine the shifted values
    combined = left_shifted | right_shifted
    
    # Mask to 32 bits
    result = combined & 0xFFFFFFFF
    
    return result


### Helper Functions

The following helper functions are used to improve the clarity of output and to verify results during testing.


In [6]:
def to_32bit_bin(val):
    """Return a 32-bit binary string with 0b prefix."""
    return format(val, '#034b')


In [7]:
def verify_output(actual, expected):
    """Compare actual and expected values and print a verification result."""
    if actual == expected:
        print("Output matches expected result.")
    else:
        print("Output does not match expected result.")


### Testing rotl(x, n=1)

The following examples test the `rotl` function with different inputs.  
Each example includes an expected output description to verify correctness.



#### Example 1

Rotate `0b00000000000000000000000000000001` (decimal 1) left by 1 position.

**Expected:**
- The single `1` bit moves to the second position.
- Result full binary (32 bits): `0b00000000000000000000000000000010`
- Shortened binary: `0b10`
- Result decimal: `2`


In [8]:
# Test Example 1
x = 0b00000000000000000000000000000001
rotated = rotl(x, 1)

print(f"Input (full binary): {to_32bit_bin(x)}")
print(f"Input (shortened binary): {bin(x)}")
print(f"Output after rotl(x, 1) (full binary): {to_32bit_bin(rotated)}")
print(f"Output after rotl(x, 1) (shortened binary): {bin(rotated)}")
print(f"Output after rotl(x, 1) (decimal): {rotated}")

# Verify result
expected = 0b10
verify_output(rotated, expected)


Input (full binary): 0b00000000000000000000000000000001
Input (shortened binary): 0b1
Output after rotl(x, 1) (full binary): 0b00000000000000000000000000000010
Output after rotl(x, 1) (shortened binary): 0b10
Output after rotl(x, 1) (decimal): 2
Output matches expected result.


#### Example 2

Rotate `0b10000000000000000000000000000000` (decimal `2^31`) left by 1 position.

**Expected:**
- The leftmost `1` bit wraps around to the rightmost position.
- Result full binary (32 bits): `0b00000000000000000000000000000001`
- Shortened binary: `0b1`
- Result decimal: `1`


In [9]:
# Test Example 2
x = 0b10000000000000000000000000000000
rotated = rotl(x, 1)

print(f"Input (full binary): {to_32bit_bin(x)}")
print(f"Input (shortened binary): {bin(x)}")
print(f"Output after rotl(x, 1) (full binary): {to_32bit_bin(rotated)}")
print(f"Output after rotl(x, 1) (shortened binary): {bin(rotated)}")
print(f"Output after rotl(x, 1) (decimal): {rotated}")

# Verify result
expected = 0b1
verify_output(rotated, expected)


Input (full binary): 0b10000000000000000000000000000000
Input (shortened binary): 0b10000000000000000000000000000000
Output after rotl(x, 1) (full binary): 0b00000000000000000000000000000001
Output after rotl(x, 1) (shortened binary): 0b1
Output after rotl(x, 1) (decimal): 1
Output matches expected result.


#### Example 3

Rotate `0xF0F0F0F0` (hexadecimal) left by 4 positions.

**Expected:**
- Shifting left by 4 bits moves all groups of 4 bits left by one group.
- The pattern wraps around to the right.
- Full binary before: `0b11110000111100001111000011110000`
- Full binary after rotation: `0b00001111000011110000111100001111`
- Result decimal: `252645135`


In [10]:
# Test Example 3
x = 0xF0F0F0F0
rotated = rotl(x, 4)

print(f"Input (full binary): {to_32bit_bin(x)}")
print(f"Input (shortened binary): {bin(x)}")
print(f"Output after rotl(x, 4) (full binary): {to_32bit_bin(rotated)}")
print(f"Output after rotl(x, 4) (shortened binary): {bin(rotated)}")
print(f"Output after rotl(x, 4) (decimal): {rotated}")

# Verify result
expected = 0x0F0F0F0F  # 252645135 in decimal
verify_output(rotated, expected)


Input (full binary): 0b11110000111100001111000011110000
Input (shortened binary): 0b11110000111100001111000011110000
Output after rotl(x, 4) (full binary): 0b00001111000011110000111100001111
Output after rotl(x, 4) (shortened binary): 0b1111000011110000111100001111
Output after rotl(x, 4) (decimal): 252645135
Output matches expected result.


## `rotr(x, n=1)`

The `rotr` function rotates the bits of a 32-bit unsigned integer `x` to the right by `n` positions.  
Bits that are shifted out from the right are reinserted at the left.  
A bitmask of `0xFFFFFFFF` is applied to ensure the result remains a 32-bit unsigned integer.


In [11]:
def rotr(x, n=1):
    """Rotate bits of a 32-bit unsigned integer to the right by n positions."""
    
    # Shift x right by n bits
    right_shifted = (x >> n)
    
    # Shift x left by (32 - n) bits
    left_shifted = (x << (32 - n))
    
    # Combine the shifted values
    combined = right_shifted | left_shifted
    
    # Mask to 32 bits
    result = combined & 0xFFFFFFFF
    
    return result


#### Example 1

Rotate `0b00000000000000000000000000000010` (decimal 2) right by 1 position.

**Expected:**
- The single `1` bit moves one position to the right, becoming the least significant bit.
- Result full binary (32 bits): `0b00000000000000000000000000000001`
- Shortened binary: `0b1`
- Result decimal: `1`


In [12]:
# Test rotr Example 1
x = 0b00000000000000000000000000000010
rotated = rotr(x, 1)

print(f"Input (full binary): {to_32bit_bin(x)}")
print(f"Input (shortened binary): {bin(x)}")
print(f"Output after rotr(x, 1) (full binary): {to_32bit_bin(rotated)}")
print(f"Output after rotr(x, 1) (shortened binary): {bin(rotated)}")
print(f"Output after rotr(x, 1) (decimal): {rotated}")

# Verify result
expected = 0b1
verify_output(rotated, expected)


Input (full binary): 0b00000000000000000000000000000010
Input (shortened binary): 0b10
Output after rotr(x, 1) (full binary): 0b00000000000000000000000000000001
Output after rotr(x, 1) (shortened binary): 0b1
Output after rotr(x, 1) (decimal): 1
Output matches expected result.


#### Example 2

Rotate `0xF0F0F0F0` (hexadecimal) right by 4 positions.

**Expected:**
- Shifting right by 4 bits moves all groups of 4 bits right by one group.
- The pattern wraps around from the right to the left.
- Full binary before: `0b11110000111100001111000011110000`
- Full binary after rotation: `0b00001111000011110000111100001111`
- Result decimal: `252645135`


In [13]:
# Test rotr Example 2
x = 0xF0F0F0F0
rotated = rotr(x, 4)

print(f"Input (full binary): {to_32bit_bin(x)}")
print(f"Input (shortened binary): {bin(x)}")
print(f"Output after rotr(x, 4) (full binary): {to_32bit_bin(rotated)}")
print(f"Output after rotr(x, 4) (shortened binary): {bin(rotated)}")
print(f"Output after rotr(x, 4) (decimal): {rotated}")

# Verify result
expected = 0x0F0F0F0F  # 252645135 in decimal
verify_output(rotated, expected)


Input (full binary): 0b11110000111100001111000011110000
Input (shortened binary): 0b11110000111100001111000011110000
Output after rotr(x, 4) (full binary): 0b00001111000011110000111100001111
Output after rotr(x, 4) (shortened binary): 0b1111000011110000111100001111
Output after rotr(x, 4) (decimal): 252645135
Output matches expected result.


## `ch(x, y, z)`

The `ch` function chooses bits from `y` or `z` based on the bits of `x`.

For each bit position:
- If the corresponding bit in `x` is `1`, the bit from `y` is chosen.
- If the corresponding bit in `x` is `0`, the bit from `z` is chosen.

This operation is fundamental in cryptographic hash functions like SHA-256.

In [14]:
def ch(x, y, z):
    """Choose bits from y or z based on x: if bit in x is 1, take bit from y; else take bit from z."""
    
    # Select bits from y where x has 1s
    y_bits = x & y
    
    # Select bits from z where x has 0s
    z_bits = (~x) & z
    
    # Combine the results
    result = y_bits ^ z_bits
    
    return result


#### Example 1

Inputs:
- `x = 0b11110000`
- `y = 0b10101010`
- `z = 0b01010101`

**Expected:**
- For bits where `x` is `1`, take the corresponding bit from `y`.
- For bits where `x` is `0`, take the corresponding bit from `z`.

**Step-by-step:**
- First 4 bits (`1111`) → choose from `y`
- Last 4 bits (`0000`) → choose from `z`

**Result full binary:** `0b10100101`  
**Result decimal:** `165`


In [15]:
# Test ch Example 1
x = 0b11110000
y = 0b10101010
z = 0b01010101
chosen = ch(x, y, z)

print(f"x (full binary): {to_32bit_bin(x)}")
print(f"y (full binary): {to_32bit_bin(y)}")
print(f"z (full binary): {to_32bit_bin(z)}")
print(f"Output (full binary): {to_32bit_bin(chosen)}")
print(f"Output (shortened binary): {bin(chosen)}")
print(f"Output (decimal): {chosen}")

# Verify result
expected = 0b10100101
verify_output(chosen, expected)


x (full binary): 0b00000000000000000000000011110000
y (full binary): 0b00000000000000000000000010101010
z (full binary): 0b00000000000000000000000001010101
Output (full binary): 0b00000000000000000000000010100101
Output (shortened binary): 0b10100101
Output (decimal): 165
Output matches expected result.


#### Example 2

Inputs:
- `x = 0xFF00FF00`
- `y = 0xAAAAAAAA`
- `z = 0x55555555`

**Expected:**
- For each bit:
  - If `x` has `1`, take from `y`.
  - If `x` has `0`, take from `z`.

**Result:**
- In the high and low sections where `x` is `0xFF00`, bits from `y` (`0xAAAAAAAA`) are taken.
- In the middle sections where `x` is `0x00FF`, bits from `z` (`0x55555555`) are taken.

**Expected full binary output:**  
(Not won't manually listed, but will verified programmatically.)  
**Expected decimal output:** `2863267835`


In [16]:
# Test ch Example 2
x = 0xFF00FF00
y = 0xAAAAAAAA
z = 0x55555555
chosen = ch(x, y, z)

print(f"x (full binary): {to_32bit_bin(x)}")
print(f"y (full binary): {to_32bit_bin(y)}")
print(f"z (full binary): {to_32bit_bin(z)}")
print(f"Output (full binary): {to_32bit_bin(chosen)}")
print(f"Output (shortened binary): {bin(chosen)}")
print(f"Output (decimal): {chosen}")

# Verify result
expected = 0xAA55AA55  # 2863267835 in decimal
verify_output(chosen, expected)


x (full binary): 0b11111111000000001111111100000000
y (full binary): 0b10101010101010101010101010101010
z (full binary): 0b01010101010101010101010101010101
Output (full binary): 0b10101010010101011010101001010101
Output (shortened binary): 0b10101010010101011010101001010101
Output (decimal): 2857740885
Output matches expected result.


## `maj(x, y, z)`

The `maj` function computes the majority value for each bit among the three inputs `x`, `y`, and `z`.

For each bit position:
- If **at least two** of the corresponding bits in `x`, `y`, and `z` are `1`, the output bit is set to `1`.
- Otherwise, the output bit is set to `0`.

This operation is used in cryptographic algorithms like SHA-256 to combine multiple inputs securely.


In [17]:
def maj(x, y, z):
    """Compute the majority for each bit position among x, y, and z."""
    
    # Bits where both x and y are 1
    xy = x & y
    
    # Bits where both x and z are 1
    xz = x & z
    
    # Bits where both y and z are 1
    yz = y & z
    
    # Combine all majority cases
    result = (xy | xz | yz)
    
    return result


#### Example 1

Inputs:
- `x = 0b11110000`
- `y = 0b10101010`
- `z = 0b01010101`

**Expected:**
- For each bit:
  - If at least two of `x`, `y`, and `z` have `1` at that position, the output bit is `1`.
  - Otherwise, the output bit is `0`.

**Expected result full binary:** `0b11110000`  
**Expected result decimal:** `240`


In [18]:
# Test maj Example 1
x = 0b11110000
y = 0b10101010
z = 0b01010101
majority = maj(x, y, z)

print(f"x (full binary): {to_32bit_bin(x)}")
print(f"y (full binary): {to_32bit_bin(y)}")
print(f"z (full binary): {to_32bit_bin(z)}")
print(f"Output (full binary): {to_32bit_bin(majority)}")
print(f"Output (shortened binary): {bin(majority)}")
print(f"Output (decimal): {majority}")

# Verify result
expected = 0b11110000
verify_output(majority, expected)


x (full binary): 0b00000000000000000000000011110000
y (full binary): 0b00000000000000000000000010101010
z (full binary): 0b00000000000000000000000001010101
Output (full binary): 0b00000000000000000000000011110000
Output (shortened binary): 0b11110000
Output (decimal): 240
Output matches expected result.


#### Example 2

Inputs:
- `x = 0xF0F0F0F0`
- `y = 0x0F0F0F0F`
- `z = 0xFFFFFFFF`

**Expected:**
- For each bit:
  - If at least two of `x`, `y`, and `z` have `1` at that position, output `1`.
  - Otherwise, output `0`.

**Reasoning:**
- Since `z` is `0xFFFFFFFF` (all `1`s), every bit will have at least two `1`s if either `x` or `y` has a `1`.
- So the result should be:
  - Wherever `x` **OR** `y` has a `1`, output `1`.
- This is simply the bitwise `OR` of `x` and `y`.

**Expected full binary output:** `x | y` = `0xFFFFFFFF` (all 1s)

**Expected decimal output:** `4294967295`


In [19]:
# Test maj Example 2
x = 0xF0F0F0F0
y = 0x0F0F0F0F
z = 0xFFFFFFFF
majority = maj(x, y, z)

print(f"x (full binary): {to_32bit_bin(x)}")
print(f"y (full binary): {to_32bit_bin(y)}")
print(f"z (full binary): {to_32bit_bin(z)}")
print(f"Output (full binary): {to_32bit_bin(majority)}")
print(f"Output (shortened binary): {bin(majority)}")
print(f"Output (decimal): {majority}")

# Verify result
expected = 0xFFFFFFFF
verify_output(majority, expected)


x (full binary): 0b11110000111100001111000011110000
y (full binary): 0b00001111000011110000111100001111
z (full binary): 0b11111111111111111111111111111111
Output (full binary): 0b11111111111111111111111111111111
Output (shortened binary): 0b11111111111111111111111111111111
Output (decimal): 4294967295
Output matches expected result.


## Task 2: Hash Functions

The following hash function is from *The C Programming Language* by Brian Kernighan and Dennis Ritchie.  
Convert it to Python, test it, and suggest why the values 31 and 101 are used.

```c
unsigned hash(char *s) {
    unsigned hashval;
    for (hashval = 0; *s != '\0'; s++)
        hashval = *s + 31 * hashval;
    return hashval % 101;
}
```

## Overall Plan

This task involves translating a small C hash function into Python.  
The function reads a string character by character, builds a hash value, and returns the result modulo 101.

The Python version will:
- Loop through the characters of the input string.
- Apply the same arithmetic operations.
- Return the hash value modulo 101.

Test examples will be included to verify correctness.  
An explanation of the choice of constants 31 and 101 will also be provided.

## Rough Outline

- Define a Python function `hash_string(s)` that replicates the C function behavior.
- Initialize the `hashval` variable to `0`.
- Loop over each character `c` in the input string `s`:
  - Update `hashval` with the formula: `hashval = ord(c) + 31 * hashval`
    - `ord(c)` gets the ASCII integer value of the character.
- Return `hashval % 101`.
- Create test examples using a variety of short strings.
- Verify that the function returns consistent results.
- Explain the significance of the numbers:
  - `31`
  - `101`



## Understanding the Original C Hash Function

The provided C function computes a simple hash value for a given string.  
Here is what the function does, step-by-step:

1. **Initialize** a variable `hashval` to `0`.
2. **Loop** through each character `*s` in the string until the null terminator (`'\0'`) is reached.
3. **For each character**:
   - Multiply the current `hashval` by `31`.
   - Add the ASCII value of the current character (`*s`) to `hashval`.
4. **After the loop**:
   - Return the final `hashval` modulo `101`.

This hash function is simple but effective for small-scale applications.


## Translating the C Function to Python

The goal is to write a Python function that behaves identically to the original C version.

Key translation points:
- In C, strings are arrays of characters terminated by a `'\0'` null character.  
  In Python, strings are automatically managed and do not require a null terminator.
- In C, characters like `*s` are accessed by pointer dereferencing.  
  In Python, we simply loop through the string directly: `for c in s:`.
- In C, `*s` gives the ASCII code implicitly.  
  In Python, the `ord(c)` function is used to get the ASCII integer value of character `c`.
- The mathematical operations are the same:
  - Multiply the current hash value by 31.
  - Add the ASCII value of the current character.
- After processing all characters, return `hashval % 101` to constrain the result to a small range.



In [20]:
def hash_string(s):
    """Compute the hash value of a string using a polynomial rolling hash function."""
    
    # Initialize the hash value to zero
    hashval = 0
    
    # Debug: Print the initial hash value
    print(f"Initial hashval: {hashval}")
    
    # Process each character in the input string
    for c in s:
        # Store the current hash value before updating (for debugging)
        old_hashval = hashval
        
        # Update hash by multiplying current hash by 31 and adding the ASCII value
        # This creates a polynomial hash where each character contributes to the result
        hashval = ord(c) + 31 * hashval
        
        # Debug: Print each step of the calculation with detailed breakdown
        print(f"Character '{c}' (ASCII {ord(c)}): {ord(c)} + 31 * {old_hashval} = {hashval}")
    
    # Calculate the final result using modulo 101 to keep the hash in a fixed range
    result = hashval % 101
    
    # Debug: Print the final hash value before and after modulo operation
    print(f"Final hashval: {hashval}")
    print(f"After modulo 101: {result}")
    
    # Return the hash value in the range [0, 100]
    return result


### Testing hash_string

The following examples test the `hash_string` function using different input strings.
Both the raw hash output and the modulo operation are verified.

#### Test 1

Input: `"hello"`

**Expected behavior:**
- Build the hash step-by-step:
  - `'h'`: 104
  - `'e'`: 104 × 31 + 101 = 3325
  - `'l'`: 3325 × 31 + 108 = 103183
  - `'l'`: 103183 × 31 + 108 = 3198681
  - `'o'`: 3198681 × 31 + 111 = 99159122
- Final `hashval`: 99159122
- Apply modulo 101: `99159122 % 101 = 17`

**Expected output:** `17`



In [21]:
s = "hello"
expected = 17
hash_result = hash_string(s)

print(f"Input: {s}")
print(f"Hash result: {hash_result}")
verify_output(hash_result, expected)


Initial hashval: 0
Character 'h' (ASCII 104): 104 + 31 * 0 = 104
Character 'e' (ASCII 101): 101 + 31 * 104 = 3325
Character 'l' (ASCII 108): 108 + 31 * 3325 = 103183
Character 'l' (ASCII 108): 108 + 31 * 103183 = 3198781
Character 'o' (ASCII 111): 111 + 31 * 3198781 = 99162322
Final hashval: 99162322
After modulo 101: 17
Input: hello
Hash result: 17
Output matches expected result.


#### Test 2

Input: `"WORLD"`

**Expected behavior:**
- Build the hash step-by-step:
  - `'W'`: 87
  - `'O'`: 87 × 31 + 79 = 2776
  - `'R'`: 2776 × 31 + 82 = 86138
  - `'L'`: 86138 × 31 + 76 = 2670354
  - `'D'`: 2670354 × 31 + 68 = 82781042
- Final `hashval`: 82781042
- Apply modulo 101: `82781042 % 101 = 28`

**Expected output:** `28`


In [22]:
s = "WORLD"
expected = 28
hash_result = hash_string(s)

print(f"Input: {s}")
print(f"Hash result: {hash_result}")
verify_output(hash_result, expected)


Initial hashval: 0
Character 'W' (ASCII 87): 87 + 31 * 0 = 87
Character 'O' (ASCII 79): 79 + 31 * 87 = 2776
Character 'R' (ASCII 82): 82 + 31 * 2776 = 86138
Character 'L' (ASCII 76): 76 + 31 * 86138 = 2670354
Character 'D' (ASCII 68): 68 + 31 * 2670354 = 82781042
Final hashval: 82781042
After modulo 101: 28
Input: WORLD
Hash result: 28
Output matches expected result.


#### Test 3

Input: `"Theory"`

**Expected behavior:**
- Build the hash step-by-step:
  - `'T'`: 84
  - `'h'`: 104 + 31 × 84 = 2708
  - `'e'`: 101 + 31 × 2708 = 84049
  - `'o'`: 111 + 31 × 84049 = 2605630
  - `'r'`: 114 + 31 × 2605630 = 80774644
  - `'y'`: 121 + 31 × 80774644 = 2504014085
- Final `hashval`: 2504014085
- Apply modulo 101: `2504014085 % 101 = 67`

**Expected output:** `67`


In [23]:
s = "Theory"
expected = 67
hash_result = hash_string(s)

print(f"Input: {s}")
print(f"Hash result: {hash_result}")
verify_output(hash_result, expected)


Initial hashval: 0
Character 'T' (ASCII 84): 84 + 31 * 0 = 84
Character 'h' (ASCII 104): 104 + 31 * 84 = 2708
Character 'e' (ASCII 101): 101 + 31 * 2708 = 84049
Character 'o' (ASCII 111): 111 + 31 * 84049 = 2605630
Character 'r' (ASCII 114): 114 + 31 * 2605630 = 80774644
Character 'y' (ASCII 121): 121 + 31 * 80774644 = 2504014085
Final hashval: 2504014085
After modulo 101: 67
Input: Theory
Hash result: 67
Output matches expected result.


## Why 31 and 101?

In the original C hash function, the constants 31 and 101 were chosen for specific reasons:

- **31 (Multiplier):**
  - 31 is a small prime number.
  - Multiplying by a prime helps to distribute the hash values more uniformly.
  - 31 is particularly efficient in binary computation because multiplication by 31 can be optimized as `(x << 5) - x` (shift and subtract), making it fast.

- **101 (Modulo Base):**
  - 101 is a prime number.
  - Using a prime number as the modulo base reduces the chance of hash collisions (different inputs giving the same hash).
  - 101 keeps the final hash value within a small range (0–100), making it suitable for small hash tables.

Together, these choices balance **speed**, **simplicity**, and **good distribution** of hash values, especially for educational examples and small programs.


## Task 3: SHA256

Write a Python function that calculates the SHA256 padding for a given file.  
The function should take a file path as input.  
It should print, in hex, the padding that would be applied to it.  
The [specification](https://doi.org/10.6028/NIST.FIPS.180-4) states that the following should be appended to a message:  

- a`1` bit;
- enough `0` bits so the length in bits of padded message is the smallest possible multiple of 512;
- the length in bits of the original input as a big-endian 64-bit unsigned integer.

The example in the specification is a file containing the three bytes `abc`:  

```python
01100001 01100010 01100011
```

The output would be:  

```python
80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 18
```


## Overall Plan

This task involves writing a Python function that calculates the SHA256 padding for a file.  
The function must:
- Read the contents of the file as bytes.
- Calculate and apply the padding according to the SHA256 standard:
  - Append a single `1` bit (represented as `0x80` in hexadecimal).
  - Append enough `0` bits (`0x00`) so that the total length (in bits) is 64 bits less than a multiple of 512.
  - Append the original message length (in bits) as a big-endian 64-bit integer.
- Print the resulting padding bytes in hexadecimal format for verification.

Test examples will be created using small text files to validate the padding.

## Rough Outline

- Define a Python function `calculate_sha256_padding(filepath)` that accepts a file path as input.
- Open the file in **binary mode** (`'rb'`) and read its contents.
- Measure the **original message length in bits**.
- Append a single `1` bit:
  - Represented as one byte `0x80`.
- Calculate the required number of `0x00` bytes:
  - Enough so that the total length is **64 bits less than a multiple of 512 bits**.
  - Total message length (including padding but excluding the final 8 bytes) should be congruent to 448 mod 512.
- Append the original message length (in bits) as an **8-byte (64-bit) big-endian integer**.
- Output the full padding in **hexadecimal** format for clarity.
- Test the function with small input files like `"abc"` to match known examples.



## Understanding SHA256 Padding

In SHA256, messages must be padded before hashing to ensure the total length is a multiple of 512 bits.  
The padding process follows these steps:

1. **Append a single `1` bit**:  
   - In binary, this is `10000000` (one `1` bit followed by seven `0` bits).
   - In hexadecimal, it is `0x80`.
   
2. **Append enough `0` bits**:  
   - Add zero (`0x00`) bytes until the total length is **64 bits (8 bytes) less than a multiple of 512**.
   - This makes room for appending the message length at the end.

3. **Append the original message length**:  
   - Represent the original message length **in bits**, not bytes.
   - Encode it as a **64-bit big-endian integer** (8 bytes).

The final padded message length will always be a multiple of 512 bits (or 64 bytes).
This padding ensures the message structure is predictable and secure for the SHA256 algorithm.


### Helper Function: calculate_sha256_padding_from_bytes

This function takes raw message bytes as input and returns the SHA256 padding bytes.  
It follows the SHA256 padding specification:
- Appends `0x80`.
- Appends enough `0x00` bytes.
- Appends the original length (in bits) encoded as a big-endian 64-bit integer.


In [24]:
def calculate_sha256_padding_from_bytes(message_bytes):
    """Given message bytes, calculate the SHA256 padding and return it."""
    
    # Calculate the original message length in bits
    original_length_bits = len(message_bytes) * 8
    
    # Start padding with a single '1' bit followed by 7 zeros (0x80 byte)
    padding = b'\x80'
    
    # Calculate how many zero bytes are needed
    # The total message length (including 0x80 byte) must be 448 mod 512
    total_length_bits = original_length_bits + 8  # 8 bits added by 0x80
    padding_zeros_bits = (448 - total_length_bits % 512) % 512
    padding_zeros_bytes = padding_zeros_bits // 8
    
    # Add the calculated number of zero bytes
    padding += b'\x00' * padding_zeros_bytes
    
    # Append the original message length as a 64-bit big-endian integer
    length_bytes = original_length_bits.to_bytes(8, 'big')
    padding += length_bytes
    
    return padding


### Helper Function: verify_padding_length

This function checks that the total length of the original message plus the padding  
is a multiple of 512 bits, as required by SHA256.


In [25]:
def verify_padding_length(message_bytes, padding_bytes):
    """Verify that the total length (original + padding) is a multiple of 512 bits."""
    
    # Calculate total message + padding length in bits
    total_bits = (len(message_bytes) + len(padding_bytes)) * 8
    
    # Check if total length is a multiple of 512 bits
    if total_bits % 512 == 0:
        print("Total length after padding is a multiple of 512 bits.")
    else:
        print("Total length after padding is NOT a multiple of 512 bits.")


### Main Function: calculate_sha256_padding

This function reads a file in binary mode, calculates its SHA256 padding,  
prints the padding in hexadecimal format, and verifies that the final message length  
(including padding) is a multiple of 512 bits.


In [26]:
def calculate_sha256_padding(filepath):
    """Read file, calculate SHA256 padding, print hex values, and verify length."""
    
    # Step 1: Read the file contents as bytes
    with open(filepath, 'rb') as f:
        message = f.read()
    
    # Step 2: Calculate the padding for the file contents
    padding = calculate_sha256_padding_from_bytes(message)
    
    # Step 3: Print the calculated padding in hexadecimal format
    print("Padding bytes (hex):")
    print(' '.join(f'{byte:02x}' for byte in padding))
    
    # Step 4: Verify that the total padded message length is correct
    verify_padding_length(message, padding)


### Testing calculate_sha256_padding

To test the `calculate_sha256_padding` function without cluttering the repository,  
a temporary file will be created using Python's `tempfile` module.

The temporary file will contain the bytes `"abc"`, matching the example given in the SHA256 padding specification.

**Expected behavior:**
- The original bytes are:

    - `01100001 01100010 01100011`

- After appending `0x80` and enough `0x00` bytes, and then the 64-bit big-endian original length (24 bits = 3 bytes × 8):
- The printed padding (in hexadecimal) should match:

    - `80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 18`


This approach keeps the notebook self-contained, and clean.



In [27]:
# https://docs.python.org/3/library/tempfile.html
import tempfile
# https://docs.python.org/3/library/os.html#module-os
import os

# Create a temporary file with "abc" content
with tempfile.NamedTemporaryFile(delete=False) as temp_file:
    temp_file_name = temp_file.name
    temp_file.write(b"abc")
    temp_file.flush()

# Run the padding calculation and verification
calculate_sha256_padding(temp_file_name)

# Clean up (delete) the temporary file afterward
os.remove(temp_file_name)
print(f"Temporary file deleted.")



Padding bytes (hex):
80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 18
Total length after padding is a multiple of 512 bits.
Temporary file deleted.


### Test 2: SHA256 Padding for an Empty File

This test creates a temporary empty file of 0 bytes,  
then uses the `calculate_sha256_padding` function to calculate and print the padding.  
It also verifies that the final total message length is a multiple of 512 bits.

**Expected behavior:**
- The original message length is `0 bytes` (0 bits).
- Padding should start with `0x80`, followed by enough `0x00` bytes,  
  and end with the 64-bit big-endian representation of `0`.


In [28]:
# Create a temporary empty file
with tempfile.NamedTemporaryFile(delete=False) as temp_file:
    temp_file_name = temp_file.name
    temp_file.write(b"")  # Write no content
    temp_file.flush()

# Run the padding calculation and verification
calculate_sha256_padding(temp_file_name)

# Clean up (delete) the temporary file afterward
os.remove(temp_file_name)
print(f"Temporary file deleted.")


Padding bytes (hex):
80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Total length after padding is a multiple of 512 bits.
Temporary file deleted.


## Task 4: Prime Numbers

Calculate the first 1,00 prime numbers using two different algorithms.  
Any algorithms that are well-established and works correctly are okay to use.  
Explain how the algorithms work.

## Overall Plan

This task involves writing two Python functions that generate the first 100 prime numbers using existing algorithms
The functions must:
- Implement the algorithms logic
- Generate the first 100 prime numbers

Then using an existing list of the first 100 primes, the results of each function will be verified to make sure the primes generated correctly.

## Rough Outline

- Define prime numbers
- Decide two algorithms to wite as python functions
    **Potential algorithms from intial quick search**
    - Trial Division
    - Sieve of Eratosthenes
    - Sieve of Sundaram
    - Sieve of Atkin

- Choose the two **most understandable** algorithms to implement.
- Implement each algorithm cleanly in Python.
- Generate the first **100 prime numbers** using both methods.
- **Verify** that the outputs match expected known primes.
- Explain clearly how each algorithm works.

## Prime Numbers Definition

A **prime number** is a natural number greater than 1 that has no divisors other than 1 and itself.  
This means a prime number cannot be formed by multiplying two smaller natural numbers.

- The number 2 is the smallest and only even prime number.
- Examples of prime numbers: 2, 3, 5, 7, 11, 13, 17, etc.

Non-prime numbers are called **composite numbers**, meaning they have factors other than 1 and themselves.


## Relevance and Uses of Prime Numbers

Prime numbers are fundamental in many areas of mathematics and computer science, particularly in:

- **Cryptography**  
  Prime numbers are used in algorithms like RSA encryption, where security depends on the difficulty of factoring large numbers into primes.

- **Hash Functions**  
  Some hashing techniques rely on prime numbers to distribute hash values more uniformly.

Understanding and generating prime numbers is essential for both theoretical and practical applications in computing.


## Algorithm 1: Trial Division

### How Trial Division Works

Trial Division is one of the simplest methods to find prime numbers.

Steps:
- For each candidate number greater than 1:
  - Check if it is divisible by any smaller number between 2 and the square root of n.
  - If it is divisible by any of these, it is **not prime**.
  - If it is not divisible by any, it is **prime**.

### Why Check Only up to the square root of n?

If a number has a factor larger than its square root, then the corresponding smaller factor would already have been found.  
This optimization reduces the number of checks and makes the algorithm faster for larger numbers.

### Advantages and Disadvantages

- **Advantages**:
  - Simple and easy to understand.
  - Good for small numbers.

- **Disadvantages**:
  - Very slow for large ranges of numbers, but will not be a factor for this task.


In [29]:
def generate_primes_trial_division(count):
    """Generate the first 'count' prime numbers using trial division."""
    
    primes = []
    # Start checking from 2, the first prime number
    candidate = 2  
    
    while len(primes) < count:
        is_prime = True  # Assume candidate is prime until proven otherwise
        
        # Only check divisibility up to the square root of the candidate
        for divisor in range(2, int(candidate ** 0.5) + 1):
            if candidate % divisor == 0:
                # Found a divisor, not a prime
                is_prime = False
                break
        
        if is_prime:
            # If no divisors found, it is prime
            primes.append(candidate)  # If no divisors found, it is prime
        
        # Move to the next number
        candidate += 1  
    
    return primes


### Helper Function: verify_primes

This helper function compares two lists of prime numbers:  
- The list generated by an algorithm.
- A known correct list of the first 100 prime numbers.

It prints a confirmation message showing whether they match exactly.


In [30]:
correct_first_100_primes = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
    31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
    73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
    127, 131, 137, 139, 149, 151, 157, 163, 167, 173,
    179, 181, 191, 193, 197, 199, 211, 223, 227, 229,
    233, 239, 241, 251, 257, 263, 269, 271, 277, 281,
    283, 293, 307, 311, 313, 317, 331, 337, 347, 349,
    353, 359, 367, 373, 379, 383, 389, 397, 401, 409,
    419, 421, 431, 433, 439, 443, 449, 457, 461, 463,
    467, 479, 487, 491, 499, 503, 509, 521, 523, 541
]


In [31]:
def verify_primes(generated_primes, correct_primes):
    """Compare generated primes to a known correct list and print verification result."""
    
    if generated_primes == correct_primes:
        print("Generated primes match the correct list.")
    else:
        print("Generated primes do not match the correct list.")


In [32]:
# Generate primes using Trial Division
generated_primes = generate_primes_trial_division(100)

# Print all generated primes
print("Generated primes:")
print(generated_primes)

# Verify the generated primes match the correct list
verify_primes(generated_primes, correct_first_100_primes)


Generated primes:
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541]
Generated primes match the correct list.


## Algorithm 2: Sieve of Eratosthenes

### How the Sieve of Eratosthenes Works

The Sieve of Eratosthenes is an ancient and efficient method for finding prime numbers up to a given limit.

Steps:
- Start with a list of numbers from 2 up to the maximum number you want to check.
- Begin with the first number 2.
- Mark all multiples of 2 up to N.
- Move to the next number that is not eliminated and eliminate all multiples of it.
- Continue this process:
  - Always move to the next unmarked number.
  - Eliminate all of its multiples.
- Numbers that are never eliminated are prime.

### Why It Works

Every non-prime number has a prime factor smaller than itself,  
so by systematically eliminating multiples of primes, only primes remain.

### Advantages and Disadvantages

- **Advantages**:
  - Much faster than Trial Division for finding many primes.
  - Very efficient for generating all primes up to a reasonably large limit.

- **Disadvantages**:
  - Requires more memory for very large ranges, not releveant for this task.


In [33]:
def generate_primes_sieve_eratosthenes(count):
    """Generate the first 'count' prime numbers using the Sieve of Eratosthenes."""
    
    # Estimate an upper bound to find at least 'count' primes
    # (Using a simple guess — a larger number than needed — for simplicity)
    upper_bound = count * 20  # Safe rough guess for the first 100 primes
    
    # Create a boolean list "is_prime" initialized to True
    is_prime = [True] * (upper_bound + 1)
    is_prime[0] = is_prime[1] = False  # 0 and 1 are not prime numbers
    
    # Implement the sieve
    for number in range(2, int(upper_bound ** 0.5) + 1):
        if is_prime[number]:
            # Mark all multiples of 'number' as non-prime
            for multiple in range(number * number, upper_bound + 1, number):
                is_prime[multiple] = False
    
    # Collect the prime numbers
    primes = [num for num, prime in enumerate(is_prime) if prime]
    
    # Return only the first 'count' primes
    return primes[:count]


In [34]:
# Generate primes using Sieve of Eratosthenes
generated_primes_sieve = generate_primes_sieve_eratosthenes(100)

# Print all generated primes nicely
print("Generated primes using Sieve of Eratosthenes:")
print(generated_primes_sieve)

# Verify the generated primes
verify_primes(generated_primes_sieve, correct_first_100_primes)


Generated primes using Sieve of Eratosthenes:
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541]
Generated primes match the correct list.


## Task 5: Roots

Calculate the first 32 bits of the fractional part of the square roots of the first 100 prime numbers.

## Rough Plan

The goal of this task is to generate 32-bit constants based on the fractional parts of the square roots of the first 100 prime numbers.

Steps:

- Use the list of the first 100 primes generated in Task 4.
- For each prime number:
  1. Calculate its square root.
  2. Extract only the fractional part digits after the decimal point.
  3. Multiply the fractional part by 2^32, 4294967296.
  4. Take the integer part (floor the result).
- Store the results in a list.
- Print the final list of 100 constants.

Each constant will be a 32-bit unsigned integer derived predictably but appearing random — a common technique in cryptographic applications.


## Calculation Explanation

The task requires calculating the **first 32 bits** of the **fractional part** of the square roots of the first 100 prime numbers.


### What Are the "First 32 Bits of the Fractional Part"?

When a number has a fractional part, such as the square root of 2 (√2 ≈ 1.4142135...),  
its binary expansion looks something like:

`1.0110101000001...`

This task is only concerned with the **bits after the decimal point**, i.e., the fractional binary portion:
`.0110101000001...`

Each binary digit in the fractional portion represents decreasing powers of two:
- The first binary digit represents `1/2`
- The second represents `1/4`
- The third represents `1/8`
- And so on...

Capturing the **first 32 binary digits** of this fractional part gives a unique 32-bit binary sequence.


### Why Multiply by 2³²?

Multiplying the fractional part by `2³²` (which equals `4294967296`) shifts the first 32 binary digits into the integer part.  
This captures exactly what those 32 bits represent numerically.

**Example:**
- Fractional part: `0.4142135623730951`
- Multiply by `4294967296`:

`0.4142135623730951 × 4294967296 = 1779033703`

- Floor the result:
`1779033703`

This integer **1779033703** directly represents the first 32 bits of the fractional binary expansion.


In [35]:
#https://docs.python.org/3/library/math.html
import math

def calculate_sqrt_fraction_constants(primes):
    """
    Given a list of prime numbers, calculate a 32-bit constant for each one using the fractional part of its square root, multiplied by 2^32.
    
    Returns a list of 32-bit unsigned integers.
    """
    
    constants = []
    
    for prime in primes:
        # Calculate the square root of the prime
        sqrt_value = math.sqrt(prime)
        
        # Extract the fractional part by subtracting the integer part
        fractional_part = sqrt_value - math.floor(sqrt_value)
        
        # Multiply the fractional part by 2^32 to capture the first 32 bits
        scaled_value = fractional_part * (2 ** 32)
        
        # Take the integer part to get the 32-bit constant
        constant = int(scaled_value)
        
        # Add the result to the list of constants
        constants.append(constant)
    
    return constants


### Test: Verify calculate_sqrt_fraction_constants with Known Prime (√2)

This test checks whether the function `calculate_sqrt_fraction_constants()` correctly computes  
the 32-bit constant derived from the **fractional part of square root of 2**, following the method used in SHA-256.

The value is computed as:

- Let `square root of 2 = 1.4142135623730951`
- Extract fractional part: `0.4142135623730951`
- Multiply by `2³² = 4294967296`:

- `0.4142135623730951 × 4294967296 = 1779033703`

- Take the integer part: `1779033703`

**Expected output:** `1779033703`




In [36]:
# Known test input and expected output
test_primes = [2]
expected_constants = [1779033703]

# Run the function
test_result = calculate_sqrt_fraction_constants(test_primes)

# Output result and verify
print(f"Calculated constant for prime 2: {test_result[0]}")
if test_result == expected_constants:
    print("Output matches expected result.")
else:
    print("Output does not match expected result.")


Calculated constant for prime 2: 1779033703
Output matches expected result.


In [37]:

# Calculate the 32-bit constants for each prime
constants = calculate_sqrt_fraction_constants(generated_primes_sieve)

# Print header
print(f"{'Prime':>6}  {'Constant':>10}")
print("-" * 20)

# Print each prime and its corresponding constant
for prime, constant in zip(generated_primes_sieve, constants):
    print(f"{prime:>6}  {constant:>10}")


 Prime    Constant
--------------------
     2  1779033703
     3  3144134277
     5  1013904242
     7  2773480762
    11  1359893119
    13  2600822924
    17   528734635
    19  1541459225
    23  3418070365
    29  1654270250
    31  2438529370
    37   355462360
    41  1731405415
    43  2394180231
    47  3675008525
    53  1203062813
    59  2925498710
    61  3479995859
    67   796084093
    71  1830299338
    73  2336478295
    79  3814765974
    83   474308610
    89  1863934769
    97  3645816497
   101   214214161
   103   639484402
   107  1477814206
   109  1891102055
   113  2706455657
   127  1157183029
   131  1913507325
   137  3026663070
   139  3392277365
   149   887149614
   151  1237834173
   157  2276178418
   163  3294864124
   167  3963601907
   173   656899949
   179  1628171250
   181  1948300446
   191  3523054131
   193  3833017748
   197   153196534
   199   458427541
   211  2258461506
   223  4007997007
   227   285697673
   229   570139515
   233  11

## Task 6: Proof of Work

Find the word(s) in the English language with the greatest number of `0` bits at the beginning of their SHA256 hash digest.  
Include proof that any word you list is in at least one English dictionary.  

## Rough Outline

This task aims to find the English words whose SHA256 hashes begin with the greatest number of 0 bits.  
The approach has been refined to combine two online dictionaries into a single set of unique words, then process that combined list

### Download Two Online Dictionaries
- Fetch two different English wordlists from online.
- Read both into memory.

### Combine into a Unique Word Set
- Merge both lists using Python's `set()` to remove duplicates.
- Remove empty strings or non-alphabetic entries.
- Retain original casing as upper or lower case characters will change the final hash.

### Write Combined Dictionary to Temporary File
- Save the unique word set to a temporary text file for processing.
- This keeps the environment clean and reproducible.

### Process SHA256 Hashes
- Read each word from the temporary file.
- For each word:
  - Compute its SHA256 hash using `hashlib`.
  - Convert the hash to binary.
  - Count the number of **leading 0 bits**.
- Store each word with its hash and zero-bit count.

### Identify Top 10 Words
- Sort the list by number of leading 0 bits (descending).
- Keep only the top 10 words for comparison.

### Display Results
- Output a formatted table showing:
  - Word
  - SHA256 hash (truncated or full)
  - Number of leading 0 bits

### Clean Up
- Delete the temporary combined dictionary file after processing.


### Downloading Dictionaries

This retrieves two publicly available English wordlists from GitHub:

1. **DWYL Wordlist (`words_alpha.txt`)** 
   - https://github.com/dwyl/english-words?tab=readme-ov-file
   - Contains over 370,000 English words. 
   - Includes common, rare, and technical vocabulary.

2. **Google 20k Wordlist (`20k.txt`)** 
   - https://github.com/first20hours/google-10000-english
   - Contains the 20,000 most frequently used English words. 
   - Represents high-frequency, modern English usage. https://github.com/first20hours/google-10000-english

Both lists are fetched over HTTP and loaded into memory.


In [38]:
#https://docs.python.org/3/library/urllib.request.html
import urllib.request

# URLs of the two wordlists
dwyl_url = "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"
google20k_url = "https://raw.githubusercontent.com/first20hours/google-10000-english/master/20k.txt"

def download_wordlist(url):
    """Download and return a list of words from a given URL."""
    with urllib.request.urlopen(url) as response:
        text = response.read().decode('utf-8')
        return text.splitlines()

# Download DWYL wordlist
print("Downloading DWYL wordlist...")
words_dwyl = download_wordlist(dwyl_url)

# Download Google 20k wordlist
print("Downloading Google 20k wordlist...")
words_google = download_wordlist(google20k_url)

# Output list sizes
print(f"DWYL wordlist contains {len(words_dwyl)} words.")
print(f"Google 20k wordlist contains {len(words_google)} words.")


DWYL wordlist contains 370105 words.
Google 20k wordlist contains 20000 words.


### Combine and keep unique words in Wordlists

The two downloaded wordlists are combined into a single collection.  
To ensure no duplicates are processed, the words are added to a Python `set`, which automatically removes duplicates.

After combining, the total number of unique words is displayed.


In [39]:
# Combine both lists and remove duplicates using a set
combined_words_set = set(words_dwyl + words_google)

# Remove empty entries and normalize line endings
combined_words_set = {word.strip() for word in combined_words_set if word.strip()}

# Convert back to a sorted list (optional but helpful for consistency)
combined_words = sorted(combined_words_set)

# Output the total number of unique words
print(f"Combined dictionary contains {len(combined_words)} unique words.")


Combined dictionary contains 372643 unique words.


### Write Combined Dictionary to a Temporary File

The combined list of unique words is written to a temporary file.  
This allows the file to be reused later in the task for SHA256 processing, while avoiding adding any files to the repository.

The full path to the temporary file is stored for later use and the file is deleted once the task is complete.


In [44]:
# Create a temporary file and write one word per line
temp_dict_file = tempfile.NamedTemporaryFile(delete=False, mode='w', encoding='utf-8')
for word in combined_words:
    temp_dict_file.write(word + '\n')
temp_dict_file_path = temp_dict_file.name
temp_dict_file.close()

# Print path and confirmation
print(f"Temporary dictionary file created.")
print(f"Contains {len(combined_words)} unique words.")


Temporary dictionary file created.
Contains 372643 unique words.


### Hash and Score Words by Leading Zero Bits

This function reads each word from the combined dictionary file, computes its SHA256 hash, and converts the result into binary.

It then counts the number of **leading `0` bits** in the binary hash.

Each word and its corresponding leading zero bit count are stored as a tuple.  
At the end, the function returns a sorted list of the top N words with the most leading zeros.

This simulates a simplified proof-of-work mechanism similar to that used in blockchain mining.


In [46]:
#https://docs.python.org/3/library/hashlib.html
import hashlib

def find_top_sha256_zero_leaders(filepath, top_n=10):
    """
    Reads words from a file, computes their SHA256 hashes,
    and returns the top N words with the most leading zero bits in their hash.
    
    Args:
        filepath (str): Path to the dictionary file.
        top_n (int): Number of top-scoring words to return.

    Returns:
        List of tuples: (word, leading_zero_count, sha256_hash_hex)
    """
    results = []

    with open(filepath, 'r', encoding='utf-8') as file:
        for line in file:
            word = line.strip()
            if not word:
                continue  # skip empty lines

            # Encode word and compute SHA256 hash
            word_bytes = word.encode('utf-8')
            hash_bytes = hashlib.sha256(word_bytes).digest()

            # Convert hash to binary string
            binary_hash = bin(int.from_bytes(hash_bytes, byteorder='big'))[2:].zfill(256)

            # Count leading zeros
            leading_zeros = len(binary_hash) - len(binary_hash.lstrip('0'))

            # Store result
            results.append((word, leading_zeros, hash_bytes.hex()))

    # Sort by number of leading zeros, then alphabetically
    results.sort(key=lambda x: (-x[1], x[0]))

    return results[:top_n]


## Task 7: Turing Machines

Design a Turing Machine that adds `1` to a binary number on its tape.  
The machine should start at the left-most non-blank symbol.  
It should treat the right-most symbol as the least significant bit.

For example, suppose the following is on the tape at the start:

```python
100111
```

Your Turing machine should leave the following on the tape when it completes:

```python
101000
```


## Task 8: Computational Complexity

Implement **bubble sort** in Python, modifying it to count the number of comparisons made during sorting.  
Use this function to sort all permutations of the list:  

```python
L = [1, 2, 3, 4, 5]
```

For each permutation, print the permutation itself followed by the number of comparisons required to sort it.  